# Generated by Django 3.1.1 on 2020-11-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0013_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
