# Generated by Django 3.1.1 on 2020-11-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0014_follow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status1',
            field=models.BooleanField(default=False),
        ),
    ]
