# Generated by Django 3.1.1 on 2020-11-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0015_follow_status1'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=30)),
                ('post', models.ManyToManyField(blank=True, related_name='tag_post', to='restltform.People')),
            ],
        ),
    ]
