# Generated by Django 3.1.1 on 2020-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0016_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='suggested_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
