# Generated by Django 3.1.1 on 2020-11-30 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restltform', '0017_auto_20201129_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='suggest_tag',
            field=models.ManyToManyField(blank=True, related_name='suggest', to=settings.AUTH_USER_MODEL),
        ),
    ]
