# Generated by Django 3.1.1 on 2020-12-28 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0018_hashtag_suggest_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
