# Generated by Django 3.1.1 on 2021-01-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0019_people_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
